name: full-jarsigner-code-signing-flow-linux
on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ["self-hosted", "Linux", "X64"] # runs-on: ubuntu-latest
    name: Example with self-hosted Linux, executing Jarsigner Code Signing flow
    steps:
      - name: Setup Venafi CSP Driver
        id: cspdriver
        uses: qensus-labs/setup-venafi-csp@v1.0.0
        with:
          venafi-version: '24.1.0'
          venafi-csc-url: ${{ vars.TPP_CSC_URL }}
          venafi-auth-url: ${{ vars.TPP_AUTH_URL }}
          venafi-hsm-url: ${{ vars.TPP_HSM_URL }}
      - name: Display Venafi CSP Driver Cached Output Variables
        run: |
          echo "Output \"venafi-csp-cached-path\" [${{steps.cspdriver.outputs.venafi-csp-cached-path}}]"
          echo "Output \"venafi-csp-cached-version\" [${{steps.cspdriver.outputs.venafi-csp-cached-version}}]"
      - name: Check Venafi CSP Driver (version)
        run: pkcs11config --version
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Show Jarsigner Version
        run: jarsigner -version
      - name: Build Software Artifact
        run: |
          echo 'public class Foo { public static void main() { } }' > Foo.java
          javac Foo.java
          jar -cf foo.jar Foo.class
      - name: Store Software Artifact
        uses: actions/upload-artifact@v4
        with:
          name: foo.jar
          path: foo.jar
      - name: Setup Python SDK
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Venafi CSP Python Package
        run: pip install venafi-csp
      - name: Show Venafi-CSP Package Version
        run: python -mvenafi_csp.version_command
      - name: Sign Artifact with Jarsigner
        run: python -mvenafi_csp.jarsigner_sign_command
        env:
          TPP_AUTH_URL: ${{ vars.TPP_AUTH_URL }}
          TPP_HSM_URL: ${{ vars.TPP_HSM_URL }}
          TPP_USERNAME: ${{ vars.TPP_USERNAME }}
          TPP_PASSWORD: ${{ secrets.TPP_PASSWORD }}
          INPUT_PATH: foo.jar
          CERTIFICATE_LABEL: github-signer-development-codesigner
      - name: Verify Artifact with Jarsigner
        run: python -mvenafi_csp.jarsigner_verify_command
        env:
          TPP_AUTH_URL: ${{ vars.TPP_AUTH_URL }}
          TPP_HSM_URL: ${{ vars.TPP_HSM_URL }}
          TPP_USERNAME: ${{ vars.TPP_USERNAME }}
          TPP_PASSWORD: ${{ secrets.TPP_PASSWORD }}
          INPUT_PATH: foo.jar
          CERTIFICATE_LABEL: github-signer-development-codesigner
      - name: Store Signed Software Artifact
        uses: actions/upload-artifact@v4
        with:
          name: foo-signed.jar
          path: foo.jar